name: CICD - MAIN
on:
  workflow_dispatch:
  push:
    branches:
      - 'main'
jobs:
  Build:
    env:
      vault_token: ${{ secrets.vault_token }}
    uses: raghudevopsb84/roboshop-github-actions/.github/workflows/ci-main.yml@main
    with:
      appType: 'nodejs'
      appName: 'cart'
    secrets:
      vault_token: ${{ secrets.vault_token }}


